@extends('admin.layout')

@php
    $activeSection = 'cloud-backups';
    $entities = collect($cloudBackup->cloudEntities ?? []);
    $isDeleted = ! empty($cloudBackup->deleted_at);
    $status = $isDeleted ? 'Deleted' : ($cloudBackup->status?->name ?? 'Unknown');
    $formatBytes = fn ($bytes) => $bytes === null ? '—' : number_format((float) $bytes / 1048576, 2).' MB';
    $formatDate = fn ($value) => $value ? \Carbon\Carbon::parse($value)->format('d M Y, H:i') : '—';
@endphp

@section('content')
    <div class="max-w-[1200px] space-y-6">
        <section class="overflow-hidden rounded-lg border border-[#dce6ef] bg-white shadow-sm">
            <div class="flex flex-wrap items-start justify-between gap-4 border-b border-[#edf2f6] px-6 py-6"><div><h1 class="m-0 text-xl font-bold text-[#020617]">Cloud Backup: {{ $cloudBackup->uid }}</h1><p class="mt-2 text-sm text-[#64748b]">Operational detail and entity diagnostics for this cloud backup.</p></div><span class="inline-flex rounded-full border px-3 py-1 text-xs font-bold {{ $isDeleted ? 'border-rose-200 bg-rose-50 text-rose-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700' }}">{{ ucfirst(strtolower(str_replace('_', ' ', $status))) }}</span></div>
            <div class="grid gap-6 px-5 py-5 md:grid-cols-2 lg:grid-cols-4"><div><p class="text-xs font-bold uppercase text-[#64748b]">User</p><p class="mt-1 text-sm font-semibold">{{ $cloudBackup->user?->email ?? $cloudBackup->user_id }}</p></div><div><p class="text-xs font-bold uppercase text-[#64748b]">Entities</p><p class="mt-1 text-sm font-semibold">{{ number_format($entities->count()) }}</p></div><div><p class="text-xs font-bold uppercase text-[#64748b]">Expected size</p><p class="mt-1 text-sm font-semibold">{{ $formatBytes($cloudBackup->expected_size) }}</p></div><div><p class="text-xs font-bold uppercase text-[#64748b]">Resource ID</p><p class="mt-1 break-all font-mono text-xs">{{ $cloudBackup->resource_id ?? '—' }}</p></div></div>
            <div class="border-t border-[#edf2f6] bg-[#f8fafc] px-5 py-4 text-xs text-[#64748b]">Created {{ $formatDate($cloudBackup->created_at) }} · Completed {{ $formatDate($cloudBackup->completed_at) }} · Validated {{ $formatDate($cloudBackup->validated_at) }} · Last restored {{ $formatDate($cloudBackup->last_restored_at) }}</div>
        </section>
        <section class="rounded-lg border border-[#dce6ef] bg-white shadow-sm"><div class="border-b border-[#edf2f6] px-5 py-4"><h2 class="text-base font-bold">Operational Actions</h2></div><div class="flex flex-wrap gap-3 p-5"><form method="POST" action="{{ route('admin.cloud-backups.verify-now', $cloudBackup->uid) }}" onsubmit="return confirm(@js('Verify this cloud backup now? The page will wait for S3 checks to finish.'))">@csrf<button class="admin-btn admin-btn-primary" @disabled($isDeleted)>Verify Now</button></form><form method="POST" action="{{ route('admin.cloud-backups.verify', $cloudBackup->uid) }}">@csrf<button class="admin-btn admin-btn-success-soft" @disabled($isDeleted)>Queue Verify Job</button></form></div></section>
        <section class="overflow-hidden rounded-lg border border-[#dce6ef] bg-white shadow-sm"><div class="border-b border-[#edf2f6] px-5 py-4"><h2 class="text-base font-bold">Cloud Backup Entities</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[980px] border-collapse"><thead><tr class="bg-[#f8fafc]"><th class="px-4 py-3 text-left text-xs font-bold uppercase">UID</th><th class="px-4 py-3 text-left text-xs font-bold uppercase">Type</th><th class="px-4 py-3 text-left text-xs font-bold uppercase">Expected size</th><th class="px-4 py-3 text-left text-xs font-bold uppercase">Actual size</th><th class="px-4 py-3 text-left text-xs font-bold uppercase">ETag</th><th class="px-4 py-3 text-left text-xs font-bold uppercase">S3 key</th></tr></thead><tbody>@forelse ($entities as $entity)<tr><td class="border-t px-4 py-3 font-mono text-xs">{{ $entity->uid }}</td><td class="border-t px-4 py-3 text-sm">{{ $entity->mime_type }}</td><td class="border-t px-4 py-3 text-sm">{{ $formatBytes($entity->expected_size) }}</td><td class="border-t px-4 py-3 text-sm">{{ $formatBytes($entity->actual_size) }}</td><td class="border-t px-4 py-3 font-mono text-xs">{{ $entity->e_tag ?? '—' }}</td><td class="border-t px-4 py-3 break-all font-mono text-xs">{{ $entity->key }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center text-sm text-[#64748b]">No cloud entities found for this backup.</td></tr>@endforelse</tbody></table></div></section>
        <section>@include('admin.partials.confirm-delete-form', ['action' => route('admin.cloud-backups.destroy', $cloudBackup->uid), 'method' => 'DELETE', 'title' => 'Delete cloud backup', 'description' => 'This will permanently delete this cloud backup, related entities, and its Backup S3 objects.', 'buttonLabel' => 'Delete cloud backup', 'confirmValue' => 'DELETE', 'confirmLabel' => 'Type DELETE to confirm', 'modalTitle' => 'Confirm cloud backup deletion'])</section>
    </div>
@endsection